# Generated by Django 5.0.3 on 2026-04-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='agent_used',
            field=models.CharField(blank=True, help_text='Which agent handled this message', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, help_text='Classified intent', max_length=50),
        ),
    ]
