# Generated by Django 5.0.3 on 2026-04-08 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_mgdl', models.PositiveIntegerField()),
                ('measurement_context', models.CharField(choices=[('fasting', 'Fasting'), ('before_meal', 'Before meal'), ('after_meal', 'After meal'), ('bedtime', 'Bedtime'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='InsulinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insulin_type', models.CharField(choices=[('bolus', 'Bolus'), ('basal', 'Basal'), ('correction', 'Correction')], max_length=20)),
                ('insulin_brand', models.CharField(blank=True, max_length=100)),
                ('injection_site', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insulin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('estimated_carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carb_source', models.CharField(choices=[('manual', 'Manual'), ('ai_text', 'AI (text)'), ('ai_image', 'AI (image)'), ('ai_audio', 'AI (audio)')], default='manual', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
