# Generated by Django 5.0.3 on 2026-04-08 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BolusCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbohydrates_g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('current_glucose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_glucose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icr_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isf_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meal_dose', models.DecimalField(decimal_places=2, max_digits=6)),
                ('correction_dose', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_dose', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('meal_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.meallog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolus_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='SportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('duration_min', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('glucose_before', models.PositiveIntegerField(blank=True, null=True)),
                ('glucose_after', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
